### ISSUE TITLE
Работа на Django

### ISSUE THREAD

**Issue by sg2018rm** [iamale/sparrow-python#1]
Здравствуйте, Александр,
извините что пишу вам в issue в github, но что-то не добавились вы в скайп :) Если вам интересна работа в офисе над стартапами на Django, свяжитесь, пожалуйста, со мной в скайпе - sg2018rm@gmail.com (именно такой скайп). Или просто закройте issue если нет.
Спасибо за ваше время.

**Comment by iamale** [comment]
Привет! К сожалению, сейчас не ищу работу :)
